import type { Delivery, Complaint, CSCustomer } from "./types";

export const deliveryChartData = [
  { month: "Set/25", onTime: 15, late: 2, total: 17, percentage: 88.2 },
  { month: "Out/25", onTime: 18, late: 4, total: 22, percentage: 81.8 },
  { month: "Nov/25", onTime: 12, late: 3, total: 15, percentage: 80.0 },
  { month: "Dez/25", onTime: 10, late: 2, total: 12, percentage: 83.3 },
  { month: "Jan/26", onTime: 16, late: 3, total: 19, percentage: 84.2 },
  { month: "Fev/26", onTime: 14, late: 3, total: 17, percentage: 82.4 },
];

export const complaintCategoryData = [
  { name: "Atraso Entrega", value: 35, fill: "hsl(0 84% 60%)" },
  { name: "Defeito Produção", value: 25, fill: "hsl(45 93% 47%)" },
  { name: "Divergência Orçado", value: 20, fill: "hsl(217 91% 60%)" },
  { name: "Instalação", value: 12, fill: "hsl(25 95% 53%)" },
  { name: "Outros", value: 8, fill: "hsl(0 0% 64%)" },
];

export const npsData = [
  { month: "Set/25", promoters: 62, passives: 25, detractors: 13, nps: 49 },
  { month: "Out/25", promoters: 65, passives: 22, detractors: 13, nps: 52 },
  { month: "Nov/25", promoters: 60, passives: 28, detractors: 12, nps: 48 },
  { month: "Dez/25", promoters: 68, passives: 20, detractors: 12, nps: 56 },
  { month: "Jan/26", promoters: 72, passives: 18, detractors: 10, nps: 62 },
  { month: "Fev/26", promoters: 78, passives: 14, detractors: 8, nps: 72 },
];

export const topComplaintClients = [
  { name: "Padaria Pão Quente", count: 3 },
  { name: "TechStore Eletrônicos", count: 2 },
  { name: "Lojas Renner SA", count: 2 },
  { name: "AutoMax Concessionária", count: 1 },
  { name: "Restaurante Sabor & Arte", count: 1 },
];

export const mockDeliveries: Delivery[] = [
  {
    job: {
      id: "6983a5c88c3f7152c87b98cb",
      code: 1236,
      title: "Plotagem frota 12 veículos TransLog",
      customerName: "TransLog Logística SA",
      customerDocument: "33.444.555/0001-22",
      customerEmail: "ricardo@translog.com.br",
      customerPhone: "(51) 3111-6666",
      customerContact: "Ricardo Mendes",
      responsibleName: "Carlos Almeida",
      totalPrice: 32000.0,
      deliveryNeeded: "2026-02-15",
      deliveryDate: "2026-02-14",
      products: [{ name: "Envelopamento parcial veículos", description: "Vinil 3M IJ180 + laminação 8519", quantity: 12, totalValue: 32000 }],
    },
    deliveryStatus: "on_time",
    daysVariance: -1,
    warranty: { type: "Vinil veicular 3M — 3 anos outdoor", startDate: "2026-02-14", endDate: "2029-02-14", status: "active", daysRemaining: 1096, coverage: "Desbotamento, descolamento, bolhas, trincas do vinil", exclusions: "Danos mecânicos, lavagem com solvente, uso indevido" },
    satisfaction: { overall: 5, quality: 5, deadline: 5, service: 5, feedback: "Excelente trabalho, ficou melhor que o esperado! Já estamos pensando na próxima frota.", npsScore: 10, npsCategory: "promoter", surveyDate: "2026-02-16" },
    complaints: [],
    history: [
      { date: "2026-02-14", event: "Job finalizado e entregue ao cliente" },
      { date: "2026-02-15", event: "Pesquisa de satisfação NPS enviada por email" },
      { date: "2026-02-16", event: "NPS respondido: Promotor (nota 10)" },
    ],
  },
  {
    job: {
      id: "68dc338d9556f3500c1ad304",
      code: 1237,
      title: "Banner + Backdrop Evento Corporativo Banco XP",
      customerName: "Banco XP Eventos",
      customerDocument: "66.777.888/0001-44",
      customerEmail: "eventos@xp.com.br",
      customerPhone: "(11) 5555-9999",
      customerContact: "Camila Rodrigues",
      responsibleName: "João Silva",
      totalPrice: 12300.0,
      deliveryNeeded: "2026-02-12",
      deliveryDate: "2026-02-11",
      products: [
        { name: "Backdrop evento 5x3m", description: "Lona blackout + box truss", quantity: 1, totalValue: 6500 },
        { name: "Banners roll-up 0.8x2m", description: "Eco-solvente + estrutura retrátil", quantity: 8, totalValue: 5800 },
      ],
    },
    deliveryStatus: "on_time",
    daysVariance: -1,
    warranty: { type: "Evento — sem garantia padrão", startDate: "2026-02-11", endDate: "2026-02-11", status: "none", daysRemaining: 0, coverage: "N/A — material para uso único em evento", exclusions: "N/A" },
    satisfaction: { overall: 5, quality: 5, deadline: 5, service: 5, feedback: "Perfeito! Montagem impecável, tudo pronto antes do horário.", npsScore: 10, npsCategory: "promoter", surveyDate: "2026-02-13" },
    complaints: [],
    history: [
      { date: "2026-02-11", event: "Entrega e montagem no local do evento" },
      { date: "2026-02-12", event: "Evento realizado com sucesso" },
      { date: "2026-02-13", event: "NPS respondido: Promotor (nota 10)" },
    ],
  },
  {
    job: {
      id: "prev-job-001",
      code: 1220,
      title: "Fachada completa Loja TechStore Shopping Bourbon",
      customerName: "TechStore Eletrônicos LTDA",
      customerDocument: "22.333.444/0001-55",
      customerEmail: "expansao@techstore.com.br",
      customerPhone: "(51) 3444-5555",
      customerContact: "Fernando Azevedo",
      responsibleName: "Maria Santos",
      totalPrice: 38500.0,
      deliveryNeeded: "2026-01-20",
      deliveryDate: "2026-01-25",
      products: [
        { name: "Revestimento ACM fachada", description: "ACM 4mm preto + instalação", quantity: 1, totalValue: 22000 },
        { name: "Letras-caixa iluminadas", description: "Acrílico + LED interno", quantity: 12, totalValue: 16500 },
      ],
    },
    deliveryStatus: "late",
    daysVariance: 5,
    warranty: { type: "Fachada ACM + LED — 5 anos", startDate: "2026-01-25", endDate: "2031-01-25", status: "active", daysRemaining: 1806, coverage: "Desplacamento ACM, falha LED, desbotamento, infiltração", exclusions: "Danos por impacto, vandalismo, força maior" },
    satisfaction: { overall: 3, quality: 4, deadline: 1, service: 3, feedback: "A qualidade ficou boa, mas o atraso de 5 dias nos prejudicou na inauguração.", npsScore: 5, npsCategory: "passive", surveyDate: "2026-01-28" },
    complaints: [
      { id: "cmp-001", date: "2026-01-22", customerName: "TechStore Eletrônicos LTDA", customerDocument: "22.333.444/0001-55", jobCode: 1220, jobTitle: "Fachada completa Loja TechStore Shopping Bourbon", category: "delivery_delay", priority: "high", description: "Fachada não ficou pronta no prazo combinado.", status: "resolved", responsibleName: "Maria Santos", resolvedDate: "2026-01-26", resolution: "Equipe trabalhou fim de semana. Oferecido 10% desconto.", attachments: [] },
    ],
    history: [
      { date: "2026-01-20", event: "Prazo original — entrega não realizada" },
      { date: "2026-01-22", event: "Reclamação registrada pelo cliente" },
      { date: "2026-01-25", event: "Job finalizado e entregue (5 dias de atraso)" },
      { date: "2026-01-26", event: "Reclamação resolvida — desconto 10% oferecido" },
      { date: "2026-01-28", event: "NPS respondido: Passivo (nota 5)" },
    ],
  },
  {
    job: {
      id: "prev-job-002",
      code: 1225,
      title: "Sinalização interna Hospital São Lucas",
      customerName: "Hospital São Lucas PUCRS",
      customerDocument: "88.999.000/0001-11",
      customerEmail: "infra@saolucas.pucrs.br",
      customerPhone: "(51) 3320-3000",
      customerContact: "Dr. André Campos",
      responsibleName: "Carlos Almeida",
      totalPrice: 28900.0,
      deliveryNeeded: "2026-01-30",
      deliveryDate: "2026-01-29",
      products: [
        { name: "Placas sinalização hospitalar", description: "ACM com impressão UV + braile", quantity: 85, totalValue: 17000 },
        { name: "Totens de pavimento", description: "Aço inox escovado + ACM", quantity: 4, totalValue: 8800 },
        { name: "Faixas de piso", description: "Vinil antiderrapante impresso", quantity: 1, totalValue: 3100 },
      ],
    },
    deliveryStatus: "on_time",
    daysVariance: -1,
    warranty: { type: "Sinalização interna — 2 anos", startDate: "2026-01-29", endDate: "2028-01-29", status: "active", daysRemaining: 715, coverage: "Desbotamento, descolamento, legibilidade braile", exclusions: "Danos por limpeza com produtos abrasivos" },
    satisfaction: { overall: 5, quality: 5, deadline: 5, service: 5, feedback: "Trabalho excepcional. A sinalização em braile ficou perfeita.", npsScore: 10, npsCategory: "promoter", surveyDate: "2026-02-01" },
    complaints: [],
    history: [
      { date: "2026-01-29", event: "Entrega e instalação concluída" },
      { date: "2026-01-30", event: "Vistoria de aceite aprovada pelo cliente" },
      { date: "2026-02-01", event: "NPS respondido: Promotor (nota 10)" },
    ],
  },
  {
    job: {
      id: "prev-job-003",
      code: 1228,
      title: "Adesivagem vitrine campanha Natal - Renner (5 lojas)",
      customerName: "Lojas Renner SA",
      customerDocument: "44.555.666/0001-88",
      customerEmail: "trade-marketing@lojasrenner.com.br",
      customerPhone: "(51) 3666-1111",
      customerContact: "Patrícia Lima",
      responsibleName: "João Silva",
      totalPrice: 18500.0,
      deliveryNeeded: "2025-12-01",
      deliveryDate: "2025-12-03",
      products: [{ name: "Adesivo vitrine recorte eletrônico", description: "Vinil jateado + cores", quantity: 5, totalValue: 18500 }],
    },
    deliveryStatus: "slight_delay",
    daysVariance: 2,
    warranty: { type: "Adesivo vitrine — campanha sazonal", startDate: "2025-12-03", endDate: "2026-03-03", status: "expiring", daysRemaining: 18, coverage: "Descolamento, bolhas — remoção sem resíduos inclusa", exclusions: "Danos por limpeza com espátula metálica" },
    satisfaction: { overall: 3, quality: 4, deadline: 2, service: 3, feedback: "Qualidade visual ótima, mas 2 dias de atraso complicou campanha de Black Friday.", npsScore: 6, npsCategory: "passive", surveyDate: "2025-12-10" },
    complaints: [
      { id: "cmp-002", date: "2025-12-15", customerName: "Lojas Renner SA", customerDocument: "44.555.666/0001-88", jobCode: 1228, jobTitle: "Adesivagem vitrine campanha Natal", category: "production_defect", priority: "medium", description: "Bolhas apareceram na vitrine da loja Bourbon Wallig após 12 dias.", status: "resolved", responsibleName: "João Silva", resolvedDate: "2025-12-18", resolution: "Reaplicação gratuita da vitrine da loja 3.", attachments: [] },
    ],
    history: [
      { date: "2025-12-01", event: "Prazo original — 3 lojas entregues, 2 pendentes" },
      { date: "2025-12-03", event: "Todas as 5 lojas concluídas (2 dias atraso)" },
      { date: "2025-12-10", event: "NPS respondido: Passivo (nota 6)" },
      { date: "2025-12-15", event: "Reclamação: bolhas na loja Bourbon Wallig" },
      { date: "2025-12-18", event: "Reaplicação gratuita realizada — garantia" },
    ],
  },
  {
    job: {
      id: "prev-job-004",
      code: 1232,
      title: "Painel LED outdoor P10 - Concessionária AutoMax",
      customerName: "AutoMax Concessionária",
      customerDocument: "11.222.333/0001-99",
      customerEmail: "marketing@automax.com.br",
      customerPhone: "(51) 3222-8888",
      customerContact: "Gustavo Pereira",
      responsibleName: "Maria Santos",
      totalPrice: 52000.0,
      deliveryNeeded: "2026-02-10",
      deliveryDate: "2026-02-10",
      products: [
        { name: "Painel LED P10 outdoor 6x3m", description: "Full color + software de gestão", quantity: 1, totalValue: 42000 },
        { name: "Instalação + aterramento", description: "Estrutura metálica + elétrica", quantity: 1, totalValue: 10000 },
      ],
    },
    deliveryStatus: "on_time",
    daysVariance: 0,
    warranty: { type: "Painel LED — 2 anos módulos + 5 anos estrutura", startDate: "2026-02-10", endDate: "2028-02-10", status: "active", daysRemaining: 727, coverage: "Módulos LED defeituosos, fonte de alimentação, placa controladora", exclusions: "Surto elétrico sem DPS, vandalismo" },
    satisfaction: { overall: 4, quality: 5, deadline: 5, service: 4, feedback: "Painel incrível, qualidade de imagem excelente. Só faltou treinamento mais detalhado.", npsScore: 8, npsCategory: "passive", surveyDate: "2026-02-13" },
    complaints: [
      { id: "cmp-003", date: "2026-02-12", customerName: "AutoMax Concessionária", customerDocument: "11.222.333/0001-99", jobCode: 1232, jobTitle: "Painel LED outdoor P10", category: "other", priority: "medium", description: "Software de gestão complexo. Solicita treinamento adicional.", status: "in_progress", responsibleName: "Maria Santos", resolvedDate: null, resolution: null, attachments: [] },
    ],
    history: [
      { date: "2026-02-10", event: "Instalação finalizada no prazo" },
      { date: "2026-02-12", event: "Reclamação: pedido de treinamento software" },
      { date: "2026-02-13", event: "NPS respondido: Passivo (nota 8)" },
      { date: "2026-02-14", event: "Treinamento agendado para 17/02" },
    ],
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: "RCL-001",
    date: "2026-01-22",
    customerName: "TechStore Eletrônicos LTDA",
    customerDocument: "22.333.444/0001-55",
    jobCode: 1220,
    jobTitle: "Fachada completa Loja TechStore Shopping Bourbon",
    category: "delivery_delay",
    priority: "high",
    description: "Fachada não ficou pronta no prazo de 20/01. Inauguração da loja era dia 21/01 e tivemos que remarcar o evento para dia 26/01, gerando custos adicionais com buffet e convites.",
    status: "resolved",
    responsibleName: "Maria Santos",
    resolvedDate: "2026-01-26",
    resolution: "Equipe trabalhou sábado e domingo para finalizar. Oferecido 10% desconto no próximo projeto como compensação.",
    attachments: [],
  },
  {
    id: "RCL-002",
    date: "2025-12-15",
    customerName: "Lojas Renner SA",
    customerDocument: "44.555.666/0001-88",
    jobCode: 1228,
    jobTitle: "Adesivagem vitrine campanha Natal - Renner (5 lojas)",
    category: "production_defect",
    priority: "medium",
    description: "Bolhas apareceram na vitrine da loja Bourbon Wallig após 12 dias da aplicação. Provável problema de temperatura durante aplicação (dia estava muito frio, ~8°C).",
    status: "resolved",
    responsibleName: "João Silva",
    resolvedDate: "2025-12-18",
    resolution: "Reaplicação gratuita da vitrine da loja 3 sob garantia. Implementado procedimento: não aplicar vinil com temperatura abaixo de 15°C.",
    attachments: [],
  },
  {
    id: "RCL-003",
    date: "2026-02-12",
    customerName: "AutoMax Concessionária",
    customerDocument: "11.222.333/0001-99",
    jobCode: 1232,
    jobTitle: "Painel LED outdoor P10 - Concessionária AutoMax",
    category: "other",
    priority: "medium",
    description: "Software de gestão de conteúdo do painel LED é muito complexo. Equipe de marketing não consegue trocar as artes sozinha. Solicita treinamento adicional presencial.",
    status: "in_progress",
    responsibleName: "Maria Santos",
    resolvedDate: null,
    resolution: null,
    attachments: [],
  },
  {
    id: "RCL-004",
    date: "2026-02-11",
    customerName: "Restaurante Sabor & Arte",
    customerDocument: "77.888.999/0001-44",
    jobCode: 1215,
    jobTitle: "Letreiro e fachada Restaurante Sabor & Arte",
    category: "installation",
    priority: "high",
    description: "Letreiro luminoso apresentou falha em 3 módulos LED após chuva forte. Água entrou na caixa de conexão elétrica. Possível vedação inadequada.",
    status: "open",
    responsibleName: "Carlos Almeida",
    resolvedDate: null,
    resolution: null,
    attachments: [],
  },
  {
    id: "RCL-005",
    date: "2026-02-13",
    customerName: "Clínica Odontológica SorrirMais",
    customerDocument: "55.666.777/0001-22",
    jobCode: 1230,
    jobTitle: "Sinalização interna Clínica SorrirMais",
    category: "budget_divergence",
    priority: "low",
    description: "Cliente alega que o orçamento previa 20 placas de sinalização mas foram entregues apenas 18. Diferença de 2 placas de banheiro (masculino e feminino ala B).",
    status: "open",
    responsibleName: "João Silva",
    resolvedDate: null,
    resolution: null,
    attachments: [],
  },
  {
    id: "RCL-006",
    date: "2026-02-08",
    customerName: "Padaria Pão Quente",
    customerDocument: "33.444.555/0001-66",
    jobCode: 1218,
    jobTitle: "Fachada e comunicação visual Padaria Pão Quente",
    category: "production_defect",
    priority: "critical",
    description: "Cores da impressão do painel da fachada estão completamente erradas. O vermelho da marca saiu como laranja. Cliente muito insatisfeito — é a inauguração em 3 dias.",
    status: "in_progress",
    responsibleName: "Maria Santos",
    resolvedDate: null,
    resolution: null,
    attachments: [],
  },
];

export const mockCSCustomers: CSCustomer[] = [
  { id: 791, name: "TransLog Logística SA", document: "33.444.555/0001-22", contact_person: "Ricardo Mendes", email: "ricardo@translog.com.br", phone: "(51) 3111-6666", city: "Canoas", state: "RS", total_jobs: 8, last_job_date: "2026-02-14", nps_score: 10, nps_category: "promoter", avg_satisfaction: 4.9, complaint_count: 0, open_complaints: 0, total_revenue: 185000 },
  { id: 794, name: "Banco XP Eventos", document: "66.777.888/0001-44", contact_person: "Camila Rodrigues", email: "eventos@xp.com.br", phone: "(11) 5555-9999", city: "São Paulo", state: "SP", total_jobs: 4, last_job_date: "2026-02-11", nps_score: 10, nps_category: "promoter", avg_satisfaction: 5.0, complaint_count: 0, open_complaints: 0, total_revenue: 52800 },
  { id: 800, name: "Hospital São Lucas PUCRS", document: "88.999.000/0001-11", contact_person: "Dr. André Campos", email: "infra@saolucas.pucrs.br", phone: "(51) 3320-3000", city: "Porto Alegre", state: "RS", total_jobs: 3, last_job_date: "2026-01-29", nps_score: 10, nps_category: "promoter", avg_satisfaction: 5.0, complaint_count: 0, open_complaints: 0, total_revenue: 68500 },
  { id: 801, name: "AutoMax Concessionária", document: "11.222.333/0001-99", contact_person: "Gustavo Pereira", email: "marketing@automax.com.br", phone: "(51) 3222-8888", city: "Porto Alegre", state: "RS", total_jobs: 2, last_job_date: "2026-02-10", nps_score: 8, nps_category: "passive", avg_satisfaction: 4.0, complaint_count: 1, open_complaints: 1, total_revenue: 72000 },
  { id: 795, name: "Lojas Renner SA", document: "44.555.666/0001-88", contact_person: "Patrícia Lima", email: "trade-marketing@lojasrenner.com.br", phone: "(51) 3666-1111", city: "Porto Alegre", state: "RS", total_jobs: 6, last_job_date: "2025-12-03", nps_score: 6, nps_category: "passive", avg_satisfaction: 3.5, complaint_count: 2, open_complaints: 0, total_revenue: 98000 },
  { id: 802, name: "TechStore Eletrônicos LTDA", document: "22.333.444/0001-55", contact_person: "Fernando Azevedo", email: "expansao@techstore.com.br", phone: "(51) 3444-5555", city: "Porto Alegre", state: "RS", total_jobs: 1, last_job_date: "2026-01-25", nps_score: 5, nps_category: "passive", avg_satisfaction: 3.0, complaint_count: 1, open_complaints: 0, total_revenue: 38500 },
  { id: 803, name: "Restaurante Sabor & Arte", document: "77.888.999/0001-44", contact_person: "Chef Alexandre", email: "contato@saborarte.com.br", phone: "(51) 3555-7777", city: "Porto Alegre", state: "RS", total_jobs: 1, last_job_date: "2026-02-05", nps_score: 4, nps_category: "detractor", avg_satisfaction: 2.5, complaint_count: 1, open_complaints: 1, total_revenue: 15200 },
  { id: 804, name: "Padaria Pão Quente", document: "33.444.555/0001-66", contact_person: "Sr. Antônio", email: "contato@paoquente.com.br", phone: "(51) 3666-8888", city: "Porto Alegre", state: "RS", total_jobs: 1, last_job_date: "2026-02-06", nps_score: 2, nps_category: "detractor", avg_satisfaction: 1.5, complaint_count: 1, open_complaints: 1, total_revenue: 12800 },
];
